### ISSUE TITLE
build error inside muslbase-build-base

### ISSUE THREAD

**Issue by AsavarTzeth** [mwcampbell/docker-muslbase#2]
This is beyond my ability to explain in detail. In any case, I get build errors when the muslbase-build-base container is trying to build the perl dependency.

I ran the script today, same date and time as this issue was posted (also see error for EST server time). I have posted the build errors (marked in red by the shell) bellow.

```
          CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings 
          CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings 
          CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings 
          CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings 
          CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings 
          CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings 
          CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings 
          CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings 
`sh  cflags "optimize='-O2'" dump.o`  dump.c
          CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
```

`2015/01/02 07:36:38 The command [/bin/sh -c $ROOT/src/build-prerequisites.sh && $ROOT/src/build-temporary.sh] returned a non-zero code: -1`

**Comment by AsavarTzeth** [comment]
This issue first appeared when I ran the bootstrap script on my DigitalOcean VPS. After doing some cleanup in a fork cleanup branch, and then running it on my Workstation, the issue disappeared.

I am yet to identify what may have solved this, or potentially, what would cause this to happen only on the VPS. I will do another update when I have done further testing.

**Comment by mwcampbell** [comment]
When trying to track down a problem, it's generally a bad idea to change more than one variable at a time. What happens if you run the unmodified scripts on your workstation? Is it possible that your VPS simply ran out of memory? I admit I've only ever run this on a VM on my workstation with 32 GB of RAM, with 4 GB or more allocated to the VM.

Of course, I'm looking forward to receiving your cleanup as one or more pull requests. But for the purpose of tracking down this problem, I suggest you try the unmodified scripts on your workstation.

**Comment by AsavarTzeth** [comment]
I am well aware this is a bad idea, but I easily get confused and so I decided I needed to do a cleanup before I could do any testing. I suppose I wanted to save time, since each build test take so long.

The VPS had enough memory and storage, no doubt at all. I monitored it all the time.

Yes, my next step is to test it completely unchanged. Testing it right now in fact.

Btw, have you considered a different approach to building? At this time there is a lot of building that needs to be redone each time something fails. Tracking down issues also becomes a nightmare. I would gladly look into different approaches as soon as I can wrap my head around some of the details in your scripts.

**Comment by AsavarTzeth** [comment]
If I have any questions needing answers, would you prefer I ask it here, a new issue, or another way (email, etc..)? I would keep it to a bare minimum, but sometimes I do get stuck and it would help if I could see things from your perspective.

**Comment by mwcampbell** [comment]
Email is fine; use the email address in the commit logs. Or you can private-message me on Freenode IRC; my nick is mwcampbell.

**Comment by AsavarTzeth** [comment]
Thank you, I am looking forward to working on this.

I will try to organize myself better from now on. First debug this issue, then do a minor cleanup. All in good order.

**Comment by AsavarTzeth** [comment]
Just doing some cleanup of old issues I had forgotten about.
